/* tslint:disable */
/* eslint-disable */
/**
 * API de Gestion de la Trésorerie
 * API pour la gestion de la trésorerie d\'une agence de voyage. Permet de suivre les entrées et sorties d\'argent, les réservations, les paiements, etc.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@agencevoyage.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

